acme_website:
    resource: "@AcmeWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

acme_core:
    resource: "@AcmeCoreBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
facebook_login:
    pattern: /login/check-facebook
logout:
    path:   /logout
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
